### ISSUE TITLE
Support backward compatibility for version 1.5

### ISSUE THREAD

**Issue by kulkarnn** [solidfire/solidfire-sdk-python#57]
We have built some scripts and Ansible roles based on modules that are using Solidfire SDK version 1.5. But with new versions, there seems to be change in the source that is causing all the scripts and roles to fail. We have some customers using it and were complaining about scripts and roles not working. It seems that the problem is pointing back to recent changes in SDK. If we roll back to SDK version 1.5, it all works good. 
This is causing a whole set of issues for us as no backward compatibility to SDK version 1.5 means that all the scripts and roles that are developed by us and by the customers will have to be completely re-worked.

Can we introduce the backward compatibility for Solidfire SDK version 1.5 with the new versions so it doesn't break all the scripts and modules when upgraded?

**Comment by arjun960** [comment]
To understand more about the issue you are facing, Could you please provide us with details like : 
1. To which version of SDK have you upgraded ?
2. Which version of SolidFire Element API you are using?
3. Could you give us some instances of the scripts/methods that are failing ? Can you also share the logs for the same ?

**Comment by kulkarnn** [comment]
1.	To which version of SDK have you upgraded ?
I have upgraded and tested with 1.7 and 12.3 from 1.5

    2.	Which version of SolidFire Element API you are using? 
I have tested with Element 11.7 and 12.0
    
    3.	Could you give us some instances of the scripts/methods that are failing ? Can you also share the logs for the same ?
Couple of examples:
1. When creating Snapshot Schedule, it fails with the error - "msg": "Error creating schedule: 'ScheduleInfo' object has no attribute 'minutes'".
It looks like frequency and schedule_info have been swapped in 'Schedule' object and that might be causing this.

	Version 1.7 and above:
	
    	def __init__(self,
				frequency,
				name,
				schedule_info,
				has_error=None,
				last_run_status=None,
				last_run_time_started=None,
				paused=None,
				recurring=None,
				run_next_interval=None,
				schedule_id=None,
				starting_date=None,
				to_be_deleted=None):
	
	Version 1.5:
		
        def __init__(self,
				schedule_info,
				name,
				frequency,
				last_run_time_started=None,
				has_error=None,
				run_next_interval=None,
				last_run_status=None,
				schedule_id=None,
				paused=None,
				to_be_deleted=None,
				starting_date=None,
				recurring=None):

2. Adding drives to Element cluster fails with the error - "msg": "Error adding drives: [19, 20, 21, 22, 23, 24]: add_drives() got an unexpected keyword argument 'force_during_upgrade'".
It looks like 'force_during_upgrade' and 'force_during_bin_sync' parameters have been removed from 'AddDrivesRequest'.

	Version 1.7 and above:
		
        def __init__(self,
				drives):
	
	Version 1.5:
		
        def __init__(self,
				drives,
				force_during_upgrade=None,
				force_during_bin_sync=None):
	
3. Cluster create operation fails with error - "msg": "Error creating cluster create_cluster() got an unexpected keyword argument 'rep_count'". I think this is attributed to removal of 'rep_count' parameter from 'ClusterCreateRequest'. 

	Version 1.7 and above:
		
        def __init__(self,
				mvip,
				svip,
				username,
				password,
				nodes,
				accept_eula=None,
				serial_number=None,
				order_number=None,
				attributes=None,
				enable_software_encryption_at_rest=None):
				
	Version 1.5:
		
        def __init__(self,
				mvip,
				svip,
				rep_count,
				username,
				password,
				nodes,
				accept_eula=None,
				attributes=None):

**Comment by arjun960** [comment]
**With any Solidfire SDK release, we support the Element version with which it is released and two versions before that. For example, the SDK 1.7 which released with Element 12.2 supports Element versions 10.x to 12.2. Please refer to official Solidfire SDK documentation [here ](https://github.com/solidfire/solidfire-sdk-python/) for more info.**

Regarding the above mentioned issues(PFB comments):
`1. When creating Snapshot Schedule, it fails with the error - "msg": "Error creating schedule: 'ScheduleInfo' object has no attribute 'minutes'". `

_The Python SDK gets auto generated from the apidescriptors of corresponding Element version, we suspect that the ordering of these params has been changed in the apidescriptor over the course of time._

`2. Adding drives to Element cluster fails with the error - "msg": "Error adding drives: [19, 20, 21, 22, 23, 24]: add_drives() got an unexpected keyword argument 'force_during_upgrade'".`

_This change has been brought in by Element stack. Earlier, In case of SDK 1.5 which supports Element version stack 7.0 to 10.0 , these two parameters were exposed to the end user as optional params. In recent times (SDK 1.5 to SDK 1.7 timeline), they have removed these params from the API definition hence these two params are removed from SDKs as well.
Note: These two params are still present in the apidescriptor of AddDrives API, but their visibility has been changed to “Internal” which prevents SDKs from using these params. Please refer to official Solidfire Element documentation [here ](https://docs.netapp.com/sfe-122/index.jsp) for more info._


`3. Cluster create operation fails with error - "msg": "Error creating cluster create_cluster() got an unexpected keyword argument 'rep_count'". `

_As mentioned above, rep_count parameter got deprecated in the recent Element version._

_We suggest you to upgrade your scripts to use the latest SDK methods as you are working with Element versions 11.7 through 12.0 because SDK 1.5 supports Element stack 7.0 to 10.0 only._

**Comment by kulkarnn** [comment]
Thankyou for the clarification
